# Generated by Django 3.2.19 on 2024-12-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC Address'),
        ),
    ]
