# Generated by Django 3.2.19 on 2024-12-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_numeric_ip_famo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='mac',
        ),
        migrations.AddField(
            model_name='device',
            name='mac_famo',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='FAMO Network MAC Address'),
        ),
        migrations.AddField(
            model_name='device',
            name='mac_if',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='IF Network MAC Address'),
        ),
    ]
