# Generated by Django 5.2.7 on 2025-10-30 19:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_connectortype_alter_device_id_elementtype_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipassignment',
            name='mac_norm',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='mac_norm',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='ipassignment',
            name='mac_addr',
            field=models.CharField(db_index=True, max_length=17, validators=[django.core.validators.RegexValidator(message='MAC in format XX:XX:XX:XX:XX:XX', regex='^[0-9A-Fa-f]{2}(:[0-9A-Fa-f]{2}){5}$')]),
        ),
        migrations.AlterField(
            model_name='networkinterface',
            name='mac_addr',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='MAC in format XX:XX:XX:XX:XX:XX', regex='^[0-9A-Fa-f]{2}(:[0-9A-Fa-f]{2}){5}$')]),
        ),
        migrations.CreateModel(
            name='ParameterSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('default_num', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('soft_min', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('soft_max', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('hard_min', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('hard_max', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('step', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('group', models.CharField(blank=True, max_length=120)),
                ('element_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_specs', to='devices.elementtype')),
            ],
            options={
                'ordering': ['element_type_id', 'order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ElementParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('value_num', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('soft_min', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('soft_max', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('hard_min', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('hard_max', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('step', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('group', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_custom', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='devices.element')),
                ('spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='devices.parameterspec')),
            ],
            options={
                'ordering': ['element_id', 'group', 'order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ElementParameterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('value_num', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('source', models.CharField(default='manual', max_length=40)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='devices.elementparameter')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['parameter', 'ts'], name='devices_ele_paramet_b8aacd_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='parameterspec',
            constraint=models.UniqueConstraint(fields=('element_type', 'key'), name='uq_param_spec_type_key'),
        ),
        migrations.AddIndex(
            model_name='elementparameter',
            index=models.Index(fields=['element', 'active'], name='devices_ele_element_ad0e70_idx'),
        ),
        migrations.AddIndex(
            model_name='elementparameter',
            index=models.Index(fields=['element', 'group', 'order'], name='devices_ele_element_98c0ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='elementparameter',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('element', 'key'), name='uq_active_param_key_per_element'),
        ),
    ]
