# Generated by Django 5.2.7 on 2025-12-10 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_ipassignment_mac_norm_networkinterface_mac_norm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ElementTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_tags', to='devices.element')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_tags', to='devices.tag')),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='elements', through='devices.ElementTag', to='devices.tag'),
        ),
        migrations.AddIndex(
            model_name='elementtag',
            index=models.Index(fields=['element', 'tag'], name='devices_ele_element_4bc1e3_idx'),
        ),
        migrations.AddIndex(
            model_name='elementtag',
            index=models.Index(fields=['tag'], name='devices_ele_tag_id_7fe7f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='elementtag',
            constraint=models.UniqueConstraint(fields=('element', 'tag'), name='uq_element_tag_unique'),
        ),
    ]
